include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
  
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Disable all problematic rules
    public_member_api_docs: false
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    always_use_package_imports: false
    directives_ordering: false
    eol_at_end_of_file: false
    use_colored_box: false
    avoid_redundant_argument_values: false
    deprecated_member_use: false
    prefer_int_literals: false
    omit_local_variable_types: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_positional_boolean_parameters: false
    unawaited_futures: false
    avoid_escaping_inner_quotes: false
    inference_failure_on_instance_creation: false
    unnecessary_breaks: false
    inference_failure_on_function_invocation: false
    prefer_single_quotes: false
    require_trailing_commas: false
    static_access_to_instance_member: false
    argument_type_not_assignable: false
    avoid_dynamic_calls: false
    undefined_getter: false
    unused_local_variable: false
    invalid_assignment: false
    unnecessary_lambdas: false
    unnecessary_await_in_return: false
    unused_import: false