include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable documentation requirements for faster development
    public_member_api_docs: false
    
    # Disable some rules that conflict with generated code
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    
    # Disable strict formatting rules
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    always_use_package_imports: false
    directives_ordering: false
    eol_at_end_of_file: false
    use_colored_box: false