include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    prefer_const_constructors: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false